# Generated by Django 6.1.1 on 2026-09-07 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distillery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(default='Scotland', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Whisky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abv', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cask_type', models.CharField(blank=True, max_length=255, null=True)),
                ('smoke_level', models.IntegerField(default=0)),
                ('wood_level', models.IntegerField(default=0)),
                ('fruit_level', models.IntegerField(default=0)),
                ('brine_level', models.IntegerField(default=0)),
                ('is_peated', models.BooleanField(default=False)),
                ('is_cask_strength', models.BooleanField(default=False)),
                ('distillery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiskies', to='catalog.distillery')),
            ],
        ),
    ]
