# Generated by Django 6.1.1 on 2026-09-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_vaultitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaultitem',
            old_name='date_added',
            new_name='added_at',
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='personal_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
