# Generated by Django 6.1.1 on 2026-09-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_date_added_vaultitem_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultitem',
            name='fill',
            field=models.CharField(default='100%', max_length=20),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='status',
            field=models.CharField(default='vaulted', max_length=20),
        ),
    ]
